version: "3.9"

services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=dhsdb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        build: .
        command: >
            bash -c "django-admin startproject dhs ."
        volumes:
            - ./app:/app
        ports:
            - "8000:8000"
        depends_on:
            - db