# Generated by Django 3.2.3 on 2021-05-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the object', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Few words about the object', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
