# Generated by Django 3.2.3 on 2021-05-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='category',
            field=models.CharField(blank=True, choices=[('RND', 'Research & Development'), ('AUT', 'Automobile'), ('INF', 'Infrastructure')], help_text='Category for the Object.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='credits',
            field=models.PositiveIntegerField(blank=True, help_text='Credits earned by object.', null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value of one unit of object.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='weblink',
            field=models.URLField(blank=True, help_text='Online link for the Object.', null=True),
        ),
    ]
