# Generated by Django 3.2.3 on 2021-05-23 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20210523_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='auth.user'),
            preserve_default=False,
        ),
    ]
